# Site setings
name: 'Sabina Sagynbayeva'
# description: 'Horace is a simple Jekyll theme for writers and bloggers. Explore it yourself.'
# meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: # https://ssagynbayeva.github.io 
production_url: https://ssagynbayeva.github.io
# disqus: 'justgoodthemes'
# mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'Sabina Sagynbayeva'
  image: 'authorimage.jpg'
  greetings: 'Hi there!'
  description: "My name is Sabina Sagynbayeva. I'm an Astrophysics graduate student at Stony Brook University. My prounouns are she/her/hers. It’s nice to meet you."
  bio: 'I am a PhD student studying planets and planet formation. You can read my blog here and also listen to my self-written songs on any streaming platform.'
  
# Contact form setings
email: sabina.sagynbayeva@gmail.com
contact_page_description: "If you have questions about my research or my music, want to invite me as a speaker to your event, have questions about graduate Physics and Astronomy programs, feel free to contact me!"
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'SabinaAstro'
email: 'sabina.sagynbayeva@gmail.com'
# facebook: 'username'
github: 'ssagynbayeva'
# codepen: 'username'
# dribbble: 'username'
# medium: '@username'
instagram: 'sabinka.s.a'
# pinterest: 'username'
# linkedin: 'username'
# producthunt: '@username'

# Navigation
navigation:
  - text: About
    url: /about
  - text: Research
    url: /research
  - text: Outreach
    url: /outreach
  - text: Music
    url: /music
  - text: Contact Me
    url: /contact
  - text: CV
    url: /cv
  

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
